# Generated by Django 5.2.1 on 2025-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
