# Generated by Django 5.2.1 on 2025-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_card', '0002_virtualcard_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcard',
            name='bitnob_card_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
